### ISSUE TITLE
Slack API Service

### ISSUE THREAD

**Issue by andela-marika** [andela/bp-esa-backend#2]
Create a slack service that enables users to be able to add and remove users from Slack channels.

Refer to this implementation here. 

https://github.com/IAMOTZ/Util

**Comment by Kelechukwu** [comment]
@andela-lolali Please don't forget to put @ me and detail any blockers you are having on this task here

**Comment by andela-lolali** [comment]
@Kelechukwu This is more or less a finished story save for the alteration of it's initial roadmap in which we are pulling data from allocations rather than guys from allocations hitting our endpoint. So I can't say that there are blokers. What is needed to be discussed is if the idea of pulling data is feasible in the first place or if allocation guys will reconsider hitting our endpoints
